# Default values for movies-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: pie-slingshot

configmap: mongodb-configmap

secret: mongodb-secret

Mongodb:
  name: mongodb
  username: root
  password: password
  image: mongo:5.0.2
  pullPolicy: IfNotPresent
  servicename: mongodb-servicehelm
  deploymentname: mongodb-deploymenthelm
  port: 27017
  targetPort: 27017

Movies:
  name: movies-api
  image: vinaycheguri/movies-api:0.0.2
  pullPolicy: IfNotPresent
  servicename: movies-servicehelm
  deploymentname: movies-deploymenthelm
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  nodePort: 30004


image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


#nodeSelector: {"team": "pie-slingshot"}
nodeSelector:
  team: pie-slingshot
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: "stateless"
#              operator: In
#              values:
#                - "true"

autoscaling:
  enabled: true
  keda:
    enabled: true
    pollingInterval: "30"  # check 30sec periodically for metrics data
    cooldownPeriod: "300"  # once the load decreased, it will wait for 5 min and downscale
    minReplicaCount: "1"   # should be >= replicaCount specified in values.yaml
    maxReplicaCount: "5"
    triggers:
      - type: prometheus
        metadata:
          serverAddress: http://dev-observability.aws.phenom.local/prometheus
          metricName: http_requests_per_second
          threshold: '1'
          query: sum(irate(http_server_requests_seconds_count{namespace="jobsync",service="gateway-service"}[5m])) by (service)
      - type: memory
        metadata:
          type: Utilization
          value: "80"  # hpa make sure average Utilization <=80 by adding new pods
      - type: cpu
        metadata:
          type: Utilization
          value: "80"  # hpa make sure average Utlization <=80 by adding new pods

resources:
  requests:           # Minimum resources to run our app
    cpu: 500m
    memory: 256Mi
  limits:             # Maximum resources app can use from underlying node
    cpu: 1200m
    memory: 512Mi

triggers:
  - type: cpu
    metadata:
      type: AverageValue
      value: 400m  # hpa make sure average value <=400m by adding new pods