apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap }}
  namespace: {{ .Values.namespace }}
data:
  host: {{ .Values.Mongodb.servicename}}
  database_url: {{ .Values.Mongodb.servicename}}