apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-root-username: {{ default "" .Values.Mongodb.username | b64enc | quote }}
  mongo-root-password: {{ default "" .Values.Mongodb.password | b64enc | quote }}